My next task
pluhin/sc.it-academy.by pull request #175
Opened 2019-01-15 19:00 UTC by andrei2701

2019-01-15 19:41 UTC, pluhin requested changes
See comments + I do not see all Pythons files here

2019-01-15 19:41 UTC, pluhin commented on AndreiFamishkin/01.html/task3.html
> +		<METAcharset="utf-8">
where is whitespace between meta and charset?
Could you please checks in all files

2019-01-15 19:41 UTC, pluhin commented on AndreiFamishkin/01.html/task1.html
> +<!-- начало комментария -->
In lines 17 and 30 you have two comments.
It should be one comment started from line 17 and will ended on line 30

2019-01-15 19:41 UTC, pluhin commented on AndreiFamishkin/01.html/task4.html
> +<pre>       О сколько нам открытий чудных
here need blockquote  tag http://htmlbook.ru/html/blockquote

2019-01-15 19:41 UTC, pluhin commented on AndreiFamishkin/01.html/task4.html
> +        <h2>Тег small внтури абзаца</h2>
And were is tag small inside p?

2019-01-17 17:58 UTC, pluhin commented
Any news here?

2019-01-18 16:54 UTC, andrei2701 commented
busy on job17.01.2019, 20:59, "Siarhei Pishchyk" <notifications@github.com>:Any news here?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2019-01-20 16:24 UTC, andrei2701 commented
мда

2019-01-20 16:47 UTC, pluhin reviewed
Could you please align markup all code section to  one format

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/01.html/task1.html
> +			длящийся 25 сезонов. Первая мини-серия «Good night» была показана в «Шоу Трейси Ульман» 19 апреля 1987 года.
You did not close this paragraph

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/02.table/My_happy_birthday.html
> +			<col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67">
dot is delimiter between fractional and integer

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/03.links/MaketSite/MaketSite.html
> +            <ul>
Wrong structure for nested lists

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/03.links/piton1.html
> +				<li><a href="./piton1.html" target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
do not use target blank for the links to same site

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/03.links/piton1.html
> +				<li><a href="#chapter2"><u class="bluetext">Наша первая программа</u></a></li>
need remove tag u, see description for home tasks

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/03.links/piton2.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Do not use target blank here

2019-01-20 16:47 UTC, pluhin commented on AndreiFamishkin/03.links/piton2.html
> +				<li><a href="#chapter2"><u class="bluetext">Списки</u></a></li>
need remove tag u

2019-01-20 16:49 UTC, pluhin requested changes

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/03.links/piton3.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
remove  target blank

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/03.links/piton3.html
> +				<li><a href="#chapter2"><u class="bluetext">Модули</u></a></li>
remove tag u

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton1.html
> +				<li><a href="./piton1.html" target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
remove  target blank

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton1.html
> +				<li><a href="#chapter2"><u class="bluetext">Наша первая программа</u></a></li>
remove  tag u

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton2.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
remove  target blank

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton2.html
> +				<li><a href="#chapter2"><u class="bluetext">Списки</u></a></li>
remove  tag u

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton3.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
remove  target blank

2019-01-20 16:49 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton3.html
> +				<li><a href="#chapter2"><u class="bluetext">Модули</u></a></li>
remove tag u

2019-01-22 18:08 UTC, pluhin commented
Any updates?

2019-01-23 04:57 UTC, andrei2701 commented
today will be22.01.2019, 21:09, "Siarhei Pishchyk" <notifications@github.com>:Any updates?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2019-01-24 18:08 UTC, andrei2701 commented
исправлено

2019-01-24 18:36 UTC, pluhin commented
> исправлено

Not all, see comments

2019-01-25 19:11 UTC, closed without merging