Home_work_form
pluhin/sc.it-academy.by pull request #202
Opened 2019-01-20 19:46 UTC by Kuptsov-Dmitriy

2019-01-20 20:37 UTC, pluhin requested changes

2019-01-20 20:37 UTC, pluhin commented on dkuptsov/lesson_02/Pithon_part1.html
> +          <p><strong><u><em>chmod +x hello.py</em></u></strong></p>
Do not use tag p for non-human content

2019-01-20 20:37 UTC, pluhin commented on dkuptsov/lesson_02/Site_Maket/Site_Maket.html
> +                <li><a href="./site_maket.html">Главная</a></li>
Wrong structure for nested lists

2019-01-20 21:19 UTC, Kuptsov-Dmitriy commented on dkuptsov/lesson_02/Site_Maket/Site_Maket.html
> +                <li><a href="./site_maket.html">Главная</a></li>
corrected.

2019-01-21 05:40 UTC, pluhin commented
You have  conflicts in files

2019-01-21 16:10 UTC, pluhin approved these changes
Good, approved

2019-01-21 16:10 UTC, merged