Home task: HTML 01 HTML 02
pluhin/sc.it-academy.by pull request #204
Opened 2019-01-20 20:27 UTC by MariaYakubovich

Could You please check my home work?

Thank You in advance

2019-01-20 20:31 UTC, pluhin requested changes

2019-01-20 20:31 UTC, pluhin commented on mYakubovich/HTML_02/Python_01_02.html
> +		<p><code>
Do not use tag p for non-human content

2019-01-20 20:31 UTC, pluhin commented on mYakubovich/HTML_02/Python_01_02.html
> +		<p><code>
Do not use tag p for non-human content

2019-01-20 20:31 UTC, pluhin commented on mYakubovich/HTML_02/Python_02_02.html
> +<pre><br>
in pre is it not necessary to use br, just add new line

2019-01-22 18:07 UTC, merged

2019-01-22 18:17 UTC, MariaYakubovich commented
I wanted to add my corrections at hw. should i make them? or i may continue with the next tasks?
Thank you in advance