CSS01task
pluhin/sc.it-academy.by pull request #209
Opened 2019-01-22 09:23 UTC by vladshavel

2019-01-22 10:08 UTC, vladshavel commented
User@lugin MINGW64 ~/Desktop/myworks/sc.it-academy.by/vshavel (m-sc1-59-19)      $ git remote add my https://github.com/pluhin/sc.it-academy.by.git               fatal: remote my already exists.
--


should i just to change name "my"?

2019-01-22 17:46 UTC, pluhin requested changes

2019-01-22 17:46 UTC, pluhin commented on vshavel/CssSecond/style.css
> +	text-align:left;
This is default value for any H1..6

2019-01-22 17:46 UTC, pluhin commented on vshavel/CssSecond/style.css
> +text-align:left;
This default value for article tag

2019-01-22 17:46 UTC, pluhin commented on vshavel/CssSecond/style.css
> +font-weight:normal;
Also default

2019-01-22 17:46 UTC, pluhin commented on vshavel/CssSecond/letter.html
> +	<link rel="stylesheet" href="style.css" type="text/css">
This link should be below links with font import

2019-01-22 17:46 UTC, pluhin commented on vshavel/CssSecond/style.css
> +	text-align:left;
it is default value

2019-01-23 14:49 UTC, pluhin approved these changes
Very good, approved

2019-01-23 14:49 UTC, merged