M sc1 59 19
pluhin/sc.it-academy.by pull request #213
Opened 2019-01-22 20:03 UTC by DrYarosh

Please check my homework. Thank

2019-01-22 20:33 UTC, pluhin commented
Conflicts!!!

2019-01-23 05:42 UTC, pluhin requested changes

2019-01-23 05:42 UTC, pluhin commented on ayarohovich/task-4-3.html
> +<HEAD><META charset="utf-8"><TITLE>Пример страницы</TITLE>
Where is here close part of head?

2019-01-23 05:42 UTC, pluhin commented on ayarohovich/task-4-3.html
> +
And where is body? What is the Frankenstein here?

2019-01-23 05:42 UTC, pluhin commented on ayarohovich/task-4-4.html
> +
Frankenstein

2019-01-23 05:42 UTC, pluhin commented on ayarohovich/task-4-5.html
> +
Frankenstein :)

2019-01-23 14:47 UTC, pluhin approved these changes
Good, approved

2019-01-23 14:47 UTC, merged

2019-01-23 14:57 UTC, DrYarosh commented
Thаnks

ср, 23 янв. 2019 г., 17:47 Siarhei Pishchyk <notifications@github.com>:

> *@pluhin* approved this pull request.
>
> Good, approved
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pluhin/sc.it-academy.by/pull/213#pullrequestreview-195557631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Asj7kKNIYZEzx1W8eRHcPPPnFA65BGibks5vGHX0gaJpZM4aNatK>
> .
>