06css
pluhin/sc.it-academy.by pull request #229
Opened 2019-01-27 13:05 UTC by andrei2701

2019-01-27 17:12 UTC, pluhin requested changes

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/01.html/task4.html
> +        <style>
Just one tag style with all classes

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/02.table/My_happy_birthday.html
> +			<col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67">
not comma, dot

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton2.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Why blank here? "blank" used to apply for external links

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton1.html
> +				<li><a href="./piton1.html" target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Why blank here? "blank" used to apply for external links

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/03.links/piton2.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Why blank here? "blank" used to apply for external links

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/03.links/piton3.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Why blank here? "blank" used to apply for external links

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/04.MultiMedia/piton3.html
> +                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>
Why blank here? "blank" used to apply for external links

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +										<select name="list1"  size="6" multiple id="list1">
If we use multiple, then need [] in name of variable

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +										<p>Срок хранения (года):</p>
It should be label, there are no paragraphs in this task

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +										<p>Файл:</p>
It should be label, there are no paragraphs in this task

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +<pre><i>Телефонный номер в формате
where label?
It should be label, there are no pre tags in this task

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +									<input type="text" name="number" pattern="\+375-(29|44|25|33)-[0-9]{7}" placeholder="+375-29-2544545">
Wrong pattern

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/05.Form/Form.html
> +										<input type="text" placeholder="Только русские буквы">
Where is pattern and name here?

2019-01-27 17:12 UTC, pluhin commented on AndreiFamishkin/06css/python/python_02_link.html
> +		</style>-->
What is -->?

2019-01-27 17:48 UTC, andrei2701 commented
 I used "blank" to open the link in another window27.01.2019, 20:12, "Siarhei Pishchyk" <notifications@github.com>:@pluhin requested changes on this pull request.



In AndreiFamishkin/01.html/task4.html:
> @@ -0,0 +1,91 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Пример страницы</TITLE>
+        <title>Выравнивание по центру</title>
+        <style>

Just one tag style with all classes



In AndreiFamishkin/02.table/My_happy_birthday.html:
> +<!doctype html>
+<html>
+	<head>
+		<meta charset="utf-8">
+		<title>Календарь</title>
+		<style>
+		 table {
+        margin: auto; 
+		margin-top: 180px
+   }
+		</style>
+		</head>
+	<body>
+		<table width="200" border="1">
+			<caption>Месяц моего рождения</caption>
+			<col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67">

not comma, dot



In AndreiFamishkin/04.MultiMedia/piton2.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+        <style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+            <img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 2</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/04.MultiMedia/piton1.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+		<TITLE>Ссылки</TITLE>
+		<style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+			<img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 1</h1>
+			<ul>
+				<li><a href="./piton1.html" target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/03.links/piton2.html:
> @@ -0,0 +1,64 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+        <style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+		<h1>HOW-TO: Программа на Python, Часть 2</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/03.links/piton3.html:
> @@ -0,0 +1,106 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+            <style>
+                .bluetext {
+                        color: blue;
+                }
+            </style>
+	</HEAD>
+	<BODY> 
+		<h1>HOW-TO: Программа на Python, Часть 3</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/04.MultiMedia/piton3.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+            <style>
+                .bluetext {
+                        color: blue;
+                }
+            </style>
+	</HEAD>
+	<BODY> 
+            <img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 3</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/05.Form/Form.html:
> +							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Города РБ</legend>
+										<select name="list" id="list">	
+											<optgroup label="Города РБ">
+												<option value="1">Брест</option>
+												<option value="2">Минск</option>
+												<option value="3">Витебск</option>
+											</optgroup>
+											<optgroup label="Города России">
+													<option value="4">Москва</option>
+													<option value="5">Рязань</option>
+													<option value="6">Магадан</option>
+											</optgroup>
+										</select>
+										<select name="list1"  size="6" multiple id="list1"> 	

If we use multiple, then need [] in name of variable



In AndreiFamishkin/05.Form/Form.html:
> +														<option value="6">Магадан</option>
+										</select>
+												<input type="submit" name="otpravit" value="Ok">
+								</fieldset>
+							</form>
+					</th>
+			</tr>
+			<tr align="left" valign="top">
+					<th>
+							<h4>Загрузка файла на сервер:</h4>
+							<form method="POST" enctype="multipart/form-data" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Upload</legend>
+										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>

It should be label, there are no paragraphs in this task



In AndreiFamishkin/05.Form/Form.html:
> +														<option value="4">Москва</option>
+														<option value="5">Рязань</option>
+														<option value="6">Магадан</option>
+										</select>
+												<input type="submit" name="otpravit" value="Ok">
+								</fieldset>
+							</form>
+					</th>
+			</tr>
+			<tr align="left" valign="top">
+					<th>
+							<h4>Загрузка файла на сервер:</h4>
+							<form method="POST" enctype="multipart/form-data" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Upload</legend>
+										<p>Файл:</p>

It should be label, there are no paragraphs in this task



In AndreiFamishkin/05.Form/Form.html:
> +										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Строка поиска</legend>
+										<input type="text" placeholder="Только русские буквы">
+<pre><i>Телефонный номер в формате

where label?
It should be label, there are no pre tags in this task



In AndreiFamishkin/05.Form/Form.html:
> +										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Строка поиска</legend>
+										<input type="text" placeholder="Только русские буквы">
+<pre><i>Телефонный номер в формате
++ХХХ-ХХ-ХХХХХХХ, где Х-любое число </i></pre>
+									<input type="text" name="number" pattern="\+375-(29|44|25|33)-[0-9]{7}" placeholder="+375-29-2544545">

Wrong pattern



In AndreiFamishkin/05.Form/Form.html:
> +									<legend>Upload</legend>
+										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Строка поиска</legend>
+										<input type="text" placeholder="Только русские буквы">

Where is pattern and name here?



In AndreiFamishkin/06css/python/python_02_link.html:
>  [...]

2019-01-27 17:59 UTC, andrei2701 commented
"If we use multiple, then need [] in name of variable"then we see no choice (Array)GET variables:Array ( )POST variables:Array ( [list] => 2 [list1] => Array ( [0] => 3 ) [otpravit] => Ok )list = 2list1 = Arrayotpravit = OkFILE variables:27.01.2019, 20:12, "Siarhei Pishchyk" <notifications@github.com>:@pluhin requested changes on this pull request.



In AndreiFamishkin/01.html/task4.html:
> @@ -0,0 +1,91 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Пример страницы</TITLE>
+        <title>Выравнивание по центру</title>
+        <style>

Just one tag style with all classes



In AndreiFamishkin/02.table/My_happy_birthday.html:
> +<!doctype html>
+<html>
+	<head>
+		<meta charset="utf-8">
+		<title>Календарь</title>
+		<style>
+		 table {
+        margin: auto; 
+		margin-top: 180px
+   }
+		</style>
+		</head>
+	<body>
+		<table width="200" border="1">
+			<caption>Месяц моего рождения</caption>
+			<col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67"><col width="16,67">

not comma, dot



In AndreiFamishkin/04.MultiMedia/piton2.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+        <style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+            <img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 2</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/04.MultiMedia/piton1.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+		<TITLE>Ссылки</TITLE>
+		<style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+			<img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 1</h1>
+			<ul>
+				<li><a href="./piton1.html" target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/03.links/piton2.html:
> @@ -0,0 +1,64 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+        <style>
+            .bluetext {
+                    color: blue;
+            }
+        </style>
+	</HEAD>
+	<BODY> 
+		<h1>HOW-TO: Программа на Python, Часть 2</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/03.links/piton3.html:
> @@ -0,0 +1,106 @@
+<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+            <style>
+                .bluetext {
+                        color: blue;
+                }
+            </style>
+	</HEAD>
+	<BODY> 
+		<h1>HOW-TO: Программа на Python, Часть 3</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/04.MultiMedia/piton3.html:
> +<!DOCTYPE html>
+  <HTML>
+	<HEAD>
+		<META charset="utf-8">
+        <TITLE>Ссылки</TITLE>
+            <style>
+                .bluetext {
+                        color: blue;
+                }
+            </style>
+	</HEAD>
+	<BODY> 
+            <img align="right" src="Python.png" alt="logotip" title="Python">
+		<h1>HOW-TO: Программа на Python, Часть 3</h1>
+            <ul>
+                <li><a href="./piton1.html"target="_blank"class="bluetext">Программа на Python — часть 1</a></li>

Why blank here? "blank" used to apply for external links



In AndreiFamishkin/05.Form/Form.html:
> +							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Города РБ</legend>
+										<select name="list" id="list">	
+											<optgroup label="Города РБ">
+												<option value="1">Брест</option>
+												<option value="2">Минск</option>
+												<option value="3">Витебск</option>
+											</optgroup>
+											<optgroup label="Города России">
+													<option value="4">Москва</option>
+													<option value="5">Рязань</option>
+													<option value="6">Магадан</option>
+											</optgroup>
+										</select>
+										<select name="list1"  size="6" multiple id="list1"> 	

If we use multiple, then need [] in name of variable



In AndreiFamishkin/05.Form/Form.html:
> +														<option value="6">Магадан</option>
+										</select>
+												<input type="submit" name="otpravit" value="Ok">
+								</fieldset>
+							</form>
+					</th>
+			</tr>
+			<tr align="left" valign="top">
+					<th>
+							<h4>Загрузка файла на сервер:</h4>
+							<form method="POST" enctype="multipart/form-data" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Upload</legend>
+										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>

It should be label, there are no paragraphs in this task



In AndreiFamishkin/05.Form/Form.html:
> +														<option value="4">Москва</option>
+														<option value="5">Рязань</option>
+														<option value="6">Магадан</option>
+										</select>
+												<input type="submit" name="otpravit" value="Ok">
+								</fieldset>
+							</form>
+					</th>
+			</tr>
+			<tr align="left" valign="top">
+					<th>
+							<h4>Загрузка файла на сервер:</h4>
+							<form method="POST" enctype="multipart/form-data" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Upload</legend>
+										<p>Файл:</p>

It should be label, there are no paragraphs in this task



In AndreiFamishkin/05.Form/Form.html:
> +										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Строка поиска</legend>
+										<input type="text" placeholder="Только русские буквы">
+<pre><i>Телефонный номер в формате

where label?
It should be label, there are no pre tags in this task



In AndreiFamishkin/05.Form/Form.html:
> +										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									<legend>Строка поиска</legend>
+										<input type="text" placeholder="Только русские буквы">
+<pre><i>Телефонный номер в формате
++ХХХ-ХХ-ХХХХХХХ, где Х-любое число </i></pre>
+									<input type="text" name="number" pattern="\+375-(29|44|25|33)-[0-9]{7}" placeholder="+375-29-2544545">

Wrong pattern



In AndreiFamishkin/05.Form/Form.html:
> +									<legend>Upload</legend>
+										<p>Файл:</p>
+										<input type="file"name="file_Field" dir="ltr">
+										<p>Срок хранения (года):</p>
+										<input type="number" name="srok_hranenia" maxlength="2">
+										<input type="submit" name="zagruzit" value="Загрузить"><br>
+
+								</fieldset>
+							</form>
+					</th>
+					<th>
+							<h4>Валидация данный HTML5:</h4>
+							<form method="POST" action="http://sc.it-academy.by/fe/form.php">
+								<fieldset>
+									 [...]

2019-01-27 19:07 UTC, pluhin approved these changes

2019-01-27 19:07 UTC, merged

2019-01-28 16:20 UTC, andrei2701 commented
 In connection with the workload at work, I will look at the webinars in the records, as I complete the tasks I will upload to GitHub27.01.2019, 22:07, "Siarhei Pishchyk" <notifications@github.com>:@pluhin approved this pull request.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.