home task 03-05
pluhin/sc.it-academy.by pull request #258
Opened 2019-02-03 11:25 UTC by MariaYakubovich

Could You please check my home tasks.
Thank You in advance

2019-02-03 12:00 UTC, pluhin requested changes

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_01/Python_01.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_01/Python_01.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_01/Python_02.html
> +<pre><br>
It is not necessary to use here br, just add new line

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_01/hometask_2.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_01/hometask_2.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_02/Python_01_02.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/HTML_02/Python_01_02.html
> +		<p><code>
Do not use  p tag for not human text

2019-02-03 12:00 UTC, pluhin commented on mYakubovich/css_2/list.html
> +			max-height: 4rem;}
also need to add ```line-height: 1rem;``` here

2019-02-04 18:39 UTC, MariaYakubovich commented
I'm very sorry but I have no idea how to resolve conflicts in fixed files.
Could You please help me.
Thank You in advance

2019-02-04 18:52 UTC, pluhin commented
> I'm very sorry but I have no idea how to resolve conflicts in fixed files.
> Could You please help me.
> Thank You in advance

I cannot see conflicts in your code and github too, 
This "All checks have failed" - it is from external instrument, do not worry

2019-02-04 18:52 UTC, merged