My first tasks
pluhin/sc.it-academy.by pull request #280
Opened 2019-02-13 08:13 UTC by RLobodenko

2019-02-13 09:20 UTC, RLobodenko commented
1)не понял как запустить первую программу:(Для запуска программы нужно сделать её файл исполняемым. Для
этого введите в терминале
chmod +x hello.py
в папке, в которой вы сохранили программу. Теперь запустите её.)
2) не знаю как высести второе задание на экран. (Чтобы использовать список, мы дадим команду print
months[0] или months[1] (которые выведут на экран 'Jan' или 'Feb').)
3) не смог вывести на экран третью программу( имеется ввиду же не просто открыть код программы в браузере?)

2019-02-13 18:09 UTC, pluhin commented
> 1)не понял как запустить первую программу:(Для запуска программы нужно сделать её файл исполняемым. Для
> этого введите в терминале
> chmod +x hello.py
> в папке, в которой вы сохранили программу. Теперь запустите её.)
> 2) не знаю как высести второе задание на экран. (Чтобы использовать список, мы дадим команду print
> months[0] или months[1] (которые выведут на экран 'Jan' или 'Feb').)
> 3) не смог вывести на экран третью программу( имеется ввиду же не просто открыть код программы в браузере?)

You do not need to run the code, just make html pages :)

2019-02-16 13:25 UTC, RLobodenko commented
the second home work:
1)не появляется таблица в браузере для погоды и месяца рождения, хотя ввожу  <TABLE border="1">
2)какой код вводить чтобы картинка файтона была справа и стрелочки были слева, по центру и справа?

attempt in English :)
1) the table does not appear in the browser for the weather and month of birth, although I enter <TABLE border = "1">
2) what code to enter so that the image of the phyton is on the right and the arrows are on the left, in the center and on the right?

2019-02-16 16:19 UTC, RLobodenko commented
3) какой код чтобы ссылка подсвечивалась и открывалась ( https://ru.wikipedia.org/wiki/Симпсоны )

2019-02-18 12:39 UTC, pluhin commented
> the second home work:
> 1)не появляется таблица в браузере для погоды и месяца рождения, хотя ввожу
> 
> 
> 2)какой код вводить чтобы картинка файтона была справа и стрелочки были слева, по центру и справа?
> attempt in English :)
> 
> 1. the table does not appear in the browser for the weather and month of birth, although I enter
> 
> * what code to enter so that the image of the phyton is on the right and the arrows are on the left, in the center and on the right?

1. Because your html file does not have html structure, like html, body, head tags
2. attribute ```align="center" 
arrows - just table with one row and 3 cell

2019-02-18 12:44 UTC, pluhin requested changes

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/hello.html
> +#1!/usr/bin/env python
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new 1.html
> +#!/usr/bin/env python
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new 2.html
> +
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new 3.html
> +#silly example 2...still silly, but better
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +	<P><EM>Kuprevicha, 1/1, 220141, Minsk, Belarus. Phone +375.17.2686911</EM></P>
It is tag address

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +	<P><EM>И всё-таки она вертится!</EM></P>
here quote tag

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +	<P>О сколько нам открытий чудных</P>
here blockquote tag need

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +					<P>	ТФ:Y(<i>x</i>)=e<sup><i>-iπx</i></sup>+log<sub><i>x</i></sub>4</P>
pi need to replace to mnemonic

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/04_HTML/hello.html
> +#1!/usr/bin/env python
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/04_HTML/new 1.html
> +#!/usr/bin/env python
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/04_HTML/new 2.html
> +
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/04_HTML/new 3.html
> +#silly example 2...still silly, but better
It isn't html file

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/04_HTML/доп/дополнительное.html
> +
It isn't html file 
And do not use Cyrillic for path and files  names

2019-02-18 12:44 UTC, pluhin commented on rlobodenko/02_03_04_HTML/Site.by/about/contact.html
> +<a href="../main.html">Главная</a> <br>
Are you sure? Is it  table?

2019-02-19 15:26 UTC, RLobodenko commented on rlobodenko/01_HTML/new4.html
> +	<P><EM>Kuprevicha, 1/1, 220141, Minsk, Belarus. Phone +375.17.2686911</EM></P>
Что не так?  я же использовал теги<P> и <EM>.

2019-02-19 15:33 UTC, RLobodenko commented on rlobodenko/01_HTML/new4.html
> +					<P>	ТФ:Y(<i>x</i>)=e<sup><i>-iπx</i></sup>+log<sub><i>x</i></sub>4</P>
число пи = &#928

2019-02-19 19:33 UTC, pluhin requested changes
All python files should be same as we have on example/tasks (see pdf files).
Do not need to divide them to small part

2019-02-21 19:29 UTC, RLobodenko commented
не понимаю в задании, где погода и месяц рождения, почему не появляется таблица, хотя я уже создал html структуру?

2019-02-22 12:20 UTC, pluhin commented
> не понимаю в задании, где погода и месяц рождения, почему не появляется таблица, хотя я уже создал html структуру?

See comments

2019-02-22 12:23 UTC, pluhin requested changes

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +	<P><EM>Kuprevicha, 1/1, 220141, Minsk, Belarus. Phone +375.17.2686911</EM></P>
> Что не так? я же использовал теги <Р> и <ЕМ>.

In this task need use tag address, could you open pdf file and check it

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new_31.html
> +одинаково на <a href="https://ru.wikipedia.org/wiki/Linux"> Linux</a>, <a href="https://ru.wikipedia.org/wiki/Mac_OS"> Mac</a> и <a href="https://ru.wikipedia.org/wiki/Windows"> Microsoft Windows</a>
This links should be open in new tab

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new_21.html
> +	<li><em> <a href="new_11.html">Программа на Python — часть 1</a> <br></em></li>
What br is doing here?

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new 2.html
> +	<TABLE border="1">
why two table tags here?

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new 2.html
> +	<TABLE border="1">
And why inside head tag?

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new 2.html
> +	<THEAD>
thead tag should be inside tag table

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new 2.html
> +	<TBODY>
tbody should be inside tag table

2019-02-22 12:23 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new 2.html
> +	<table align="center" width="600">
without border attribute you cannot see table

2019-02-22 16:10 UTC, pluhin requested changes
Your svg files is binary files
Do not use Cyrillic in folders/files names
Some of my comments didn't soled

2019-02-23 10:34 UTC, RLobodenko commented
не получается картинку файтона сдвинуть вправо.

2019-02-23 14:10 UTC, RLobodenko commented
а можно ли пользоваться google переводчиком в переписке проектов?

2019-02-24 08:33 UTC, pluhin commented
> а можно ли пользоваться google переводчиком в переписке проектов?

Yes

2019-02-24 08:33 UTC, pluhin commented
> не получается картинку файтона сдвинуть вправо.

Add attribute align=right

2019-02-24 11:26 UTC, RLobodenko commented
ничего если я буду загружать все файлы в один pull request?

2019-02-24 15:20 UTC, RLobodenko commented
Не вижу изменений в 3,4,5 вариантах

2019-02-25 07:39 UTC, pluhin commented
> ничего если я буду загружать все файлы в один pull request?

This is exactly what you need to do :)

2019-02-25 08:13 UTC, pluhin requested changes

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +
Where are closing tags body and html?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +	</form>
Why two forms closed here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="number" min="-2.5" max="2.5" step="0.1"> <br>
Where is name attribute here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="range" min="1" max="10"> <br>
Where is name attribute here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<!DOCTYPE html>
There is just one form tag In this file 
+
Do not use whitespace in folder/files names

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="name" placeholder="Фамилия" pattern="^[А-Я]" required autofocus SIZE="25" > <br><span></span>
Wrong pattern - just one letter

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="name" placeholder="Фамилия" pattern="^[А-Я]" required autofocus SIZE="25" > <br><span></span>
And why here empty span tag?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="name" placeholder="Имя" pattern="^[А-Я]" SIZE="20"><br><span></span>
Wrong pattern - just one letter

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="name" placeholder="Дмитриевич" pattern="^[А-Я]" SIZE="24"><br><span></span>
Wrong pattern - just one letter

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<form method="POST" action="http://sc.it-academy.by/fe/form.php">
Just one form tag here!

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="passport" placeholder="АА" SIZE="2" MAXLENGTH="2" pattern="[A-Z]{2,2}"><span></span>
type passport does not exist

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="passport" placeholder="1234567" SIZE="7" MAXLENGTH="7" pattern="[0-9]{7,7}"> <br><span></span>
type passport does not exist

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<form method="POST" action="http://sc.it-academy.by/fe/form.php">
Just one tag form here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="text" placeholder="2000" MAXLENGTH="4" pattern="[0-9]"> <br>
Wrong pattern

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<option value="1">Январь</option>
options have duplicate value

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="number" min="1" max="31" step="1"> <br>
Where is name here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<option value="1">РБ</option>
options have duplicate value

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<form method="POST" action="http://sc.it-academy.by/fe/form.php">
Just one form tag here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<form method="POST" action="http://sc.it-academy.by/fe/form.php">
Just one form tag here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<label>
There is not one label

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="checkbox" name="val_1" id="chbox1"> Рыбалка<br>
It is not radio group!!

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +	<form method="POST" action="http://sc.it-academy.by/fe/form.php">
Just one form tag here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="text" placeholder="Логин" pattern="^[A-Z]" placeholder="[A-Z]" SIZE="20" pattern="[0-9]{5,100}" placeholder="[0-9]{5,100}"> <br><span></span>
two patterns here, both are wrong

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="password" placeholder="Пароль" pattern="^[A-Z]" placeholder="[A-Z]" SIZE="20" pattern="[0-9]{10,100}" placeholder="[0-9]{10,100}"><br><span></span>
two patterns here, both are wrong

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 2.html
> +<input type="url" placeholder="Введите адрес сайта" ><br>
Where is name?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<input type="url" placeholder="+375-29-1234567"> <br>
Where are pattern and name?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<p>+ХХХ-ХХ-ХХХХХХХ, где Х - любое число</p>
Here should be label not paragraph

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<input type="email" placeholder="Только русские буквы"> <br>
where is name name pattern here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<p>Срок хранения (года):</p>
Label here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<p>Файл:</p>
Label here

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<INPUT TYPE="hidden" name="hidden_field" value="hidden">
What is hidden field doing here?

2019-02-25 08:13 UTC, pluhin commented on rlobodenko/02_03_04_HTML/new_31.html
> +	<li><em> <a href="new_11.html">Программа на Python — часть 1</a> <br></em></li>
Could you please remove br from this list

2019-02-25 16:28 UTC, RLobodenko commented on rlobodenko/05_HTML/new 1.html
> +<p>Файл:</p>
ввёл  <label> и </label> всё равно в браузере не показывается строка

2019-02-25 16:33 UTC, pluhin commented on rlobodenko/05_HTML/new 1.html
> +<p>Файл:</p>
> ввёл и всё равно в браузере не показывается строка

What do you mean? What the string?

There are not any paragraphs in the files. just labels

2019-02-25 20:01 UTC, RLobodenko commented on rlobodenko/05_HTML/new 2.html
> +<option value="1">РБ</option>
what is mean duplicate?

2019-02-25 20:20 UTC, RLobodenko commented on rlobodenko/05_HTML/new 2.html
> +<input type="checkbox" name="val_1" id="chbox1"> Рыбалка<br>
what is mean?what to fix?

2019-02-26 20:57 UTC, pluhin requested changes

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<input type="text" placeholder="Логин" pattern="[A-Za-z]" placeholder="[A-Za-z]" SIZE="20" pattern="[0-9]{5}+" placeholder="[0-9]{5}+"> <br><span> </span>
Two patterns here

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<input type="password" placeholder="Пароль" pattern="[A-Za-z]" placeholder="[A-Za-z]" SIZE="20" pattern="[0-9]{10}+" placeholder="[0-9]{10}+"><br><span> </span>
Two patterns here

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<input type="checkbox" name="val_1" id="chbox1"> Рыбалка<br>
Duplicate value of name attribute here, should be different or array

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<option value="1">США</option>
РБ and США have same value

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<input type="url" name="telephone" pattern="\+375-(29|44|25)-[0-9]{7}" placeholder="+375-29-1234567"> <br>
wrong pattern

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<label>+ХХХ-ХХ-ХХХХХХХ, где Х - любое число</label><br>
One label tag here, and you forgot about for attribute

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<p>Срок хранения (года):</p>
label here, no paragraph

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<p>Файл:</p>
label here

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<p><input type="radio" name="date_voite" value="2013.12.31" id="Checkbox_Group1_0" checked> ничего</p>
why in the here we have identical value and name? Does not matter what you choose, will be same

2019-02-26 20:57 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<input type="password" name="password"><span>*</span>
where is id? your label does not work here without id

2019-03-01 04:41 UTC, pluhin approved these changes

2019-03-01 04:42 UTC, merged