01.HTML
pluhin/sc.it-academy.by pull request #287
Opened 2019-02-19 19:18 UTC by ISergeyN

Добрый вечер Сергей. 
Посмотрите мое задание. Спасибо.

2019-02-20 19:00 UTC, pluhin requested changes

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	#
here should be code section

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	Это комментарий
paragraph here

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	Например:
paragraph here

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task04_(04.02.19)_Ilyenka_Siarhei.html
> +<p>ТФ: Y(x)=e<sup>-iπx</sup>+log<sub>x</sub>4</p>
pi need to replace to mnemonic

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task04_(04.02.19)_Ilyenka_Siarhei.html
> +<pre><font face='Times New Roman'>	О сколько нам открытий чудных
bolockquote tag here

2019-02-20 19:00 UTC, pluhin commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	Комментарии можно вставлять в любое место в строке, но помните, что Python
paragraph here

2019-02-20 19:18 UTC, ISergeyN commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	#
Так я все сразу обернул с 57 по 70. Или все токи каждый элемент абзаца расценивать как  отдельный ТЕГ?

2019-02-21 18:02 UTC, ISergeyN commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	Это комментарий
Добрый вечер.
Исправил замечания.

2019-02-22 10:52 UTC, pluhin requested changes

2019-02-22 10:52 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +<table border="2px solid black" width="500" height="50" align="center">
Just number inside border, described by your structure relates to CSS

2019-02-22 10:52 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Брест</strong></td>
here th tag

2019-02-22 10:52 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
Missing "for"

2019-02-22 10:52 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +<table border="=2px solid black" width="220" height="50" align="center">
border - value just number

2019-02-22 16:49 UTC, ISergeyN commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
Сергей поясните, что вы имеете в ивду ? Не могу понять причем тут цикл for.

2019-02-22 16:50 UTC, ISergeyN commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
в виду.

2019-02-23 15:54 UTC, ISergeyN commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
Сергей все я понял в чем ошибка. ))

2019-02-24 08:34 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
It is cell-header, not td + center + b, just th

2019-02-24 15:02 UTC, ISergeyN commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<td align="center"><strong>Минск</strong></td>
Я вроде исправил на th.  Или я что то не правильно понял?

2019-02-25 07:37 UTC, pluhin approved these changes
Good, approved

2019-02-25 07:37 UTC, merged