SIlyenka_05.HTML(Forms)
pluhin/sc.it-academy.by pull request #304
Opened 2019-02-26 19:16 UTC by ISergeyN

Задание 5.HTML

2019-02-26 20:46 UTC, pluhin requested changes

2019-02-26 20:46 UTC, pluhin commented on SIlyenka/01.HTML/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	<p>#</p>
It is not paragraph - it is code

2019-02-26 20:46 UTC, pluhin commented on SIlyenka/01.HTML/Task04_(04.02.19)_Ilyenka_Siarhei.html
> +&#8194x&#8194|&#8194o&#8194|<br>‐‐‐‐‐‐‐‐‐‐‐<br>&#8194&#8194&#8194|&#8194х&#8194|<br>‐‐‐‐‐‐‐‐‐‐‐<br>&#8194o&#8194|&#8194x&#8194|&#8194o
here should be tag pre

2019-02-26 20:46 UTC, pluhin commented on SIlyenka/02.HTML/02.HTML(Tables).Ilyenka_Siarhei.html
> +		<th width="16%">Пн</th>
to set column with, could you please use col tag

2019-02-26 20:46 UTC, pluhin commented on SIlyenka/03.HTML(links)/Task01_(04.02.19)_Ilyenka_Siarhei.html
> +<a name="Cycle_example_For"><h2>Пример цикла For</h2></a>
Inline tags should be inside blocks tags

2019-02-26 20:46 UTC, pluhin commented on SIlyenka/03.HTML(links)/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	<p>#</p>
it is code

2019-02-27 05:21 UTC, ISergeyN commented on SIlyenka/03.HTML(links)/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	<p>#</p>
Доброго дня Сергей. 
Я послал (05.HTML_Task_01(Forms)_Ilyenka_Siarhei.html и 05.HTML_Task_02(questionnaire)_Ilyenka_Siarhei.html) эти файлы. Пока до конца не разобрался с Gituhub. Вроде у меня появились эти файлы, а на вашей стороне я нре могу их увидеть, что они стоят в очереди на рассмотрении. Вот и путаюсь где их можно увидеть. ((((

2019-02-28 05:10 UTC, pluhin commented on SIlyenka/03.HTML(links)/Task02_(04.02.19)_Ilyenka_Siarhei.html
> +	<p>#</p>
If your PR did not merged, you can see your code just in your repos

2019-03-01 13:54 UTC, pluhin commented
Any changes?

2019-03-08 12:58 UTC, pluhin requested changes

2019-03-08 12:58 UTC, pluhin commented on SIlyenka/05.HTML(Forms)/05.HTML_Task_01(Forms)_Ilyenka_Siarhei.html
> +		<select name="list[]" id="list" size="8" multiple > <!--[] - можно отправить сразу массив данных -->
Name is duplicating with line 110, it not good in one form

2019-03-08 12:58 UTC, pluhin commented on SIlyenka/05.HTML(Forms)/05.HTML_Task_01(Forms)_Ilyenka_Siarhei.html
> +		<span>Срок храненния (года):</span><br>
It is label

2019-03-10 17:21 UTC, merged