Home tasks by Roman Lobodenko
pluhin/sc.it-academy.by pull request #316
Opened 2019-03-03 11:15 UTC by RLobodenko

2019-03-04 08:03 UTC, pluhin requested changes

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/01_CSS/new1.html
> +<!DOCTYPE html>
Where is font declaration from googlefonts site?

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/01_HTML/new4.html
> +<P>‐‐‐‐‐‐‐‐‐‐‐</P>
here pre tag

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<input type="text" placeholder="Логин" pattern="[A-Za-z]{5}+" placeholder="[A-Za-z]{5}+" SIZE="20"> <br><span> </span>
where is name?

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/05_HTML/new_2.html
> +<input type="password" placeholder="Пароль" pattern="[A-Za-z]{10}+" placeholder="[A-Za-z]{10}+" SIZE="20"><br><span> </span>
where is name here

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<label>Телефонный номер в формате<br>
label for?

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<label>Срок хранения (года):</label>
label for?

2019-03-04 08:03 UTC, pluhin commented on rlobodenko/05_HTML/new_1.html
> +<label>Файл:</label>
label for?

2019-03-04 16:16 UTC, RLobodenko commented
Почему в файле 05_HTML/new_1.html в задании upload не показывает строку загрузки?

2019-03-04 16:19 UTC, RLobodenko commented
Why in the file 05_HTML / new_1.html in the task upload does not show the download string?

2019-03-06 19:05 UTC, pluhin commented
You have conflicts, could you resolve them

2019-03-08 12:38 UTC, pluhin commented
> Why in the file 05_HTML / new_1.html in the task upload does not show the download string?

What do you mean "download string"? Status bar? Progress of downloading?

2019-03-08 12:50 UTC, RLobodenko commented
..спросил этот вопрос в slack'е

2019-03-11 16:29 UTC, merged