FW&JQ
pluhin/sc.it-academy.by pull request #345
Opened 2019-03-16 14:20 UTC by RLobodenko

2019-03-16 14:22 UTC, RLobodenko commented
для задания базового №1 взял материал отсюда, но не довёл до ума, помогите.
https://htmlacademy.ru/blog/95-form-validation-techniques
https://javascript.ru/forum/misc/31346-kak-sravnit-stroki.html

2019-03-16 16:47 UTC, pluhin commented
> для задания базового №1 взял материал отсюда, но не довёл до ума, помогите.
> https://htmlacademy.ru/blog/95-form-validation-techniques
> https://javascript.ru/forum/misc/31346-kak-sravnit-stroki.html

Example: 
```js

$(document).ready(function(){
--
  | $('#pass1, #pass2').on('keyup', function () {
  | if ($('#pass1').val() != $('#pass2').val()) {
  | $('#pass1,#pass2').removeClass().addClass('wrong');
  | $('#message').html('Not Matching Passwords').css('color', 'red');
  | } else {
  | $('#pass1,#pass2').removeClass().addClass('right');
  | $('#message').html('Matching Passwords').css('color', 'green');
  | }
  | });
  | });


```

2019-03-16 16:57 UTC, pluhin requested changes

2019-03-16 16:57 UTC, pluhin commented on rlobodenko/01_FW_&_JQ/JQ-table.html
> +			$('.tr').click(function(){
Is it not correct solution
Example 
```
 $(function(){
                    var button_label_01 = 'We have hidden lines in table. Just click me, and I show them';
                    var button_label_02 = 'There are no hidden lines in table';       
                    $('caption').addClass('h2');
                    $('#table_data').addClass('table table-hover table-light');
                    $('.display_button').addClass('btn btn-primary btn-sm  btn-block disabled');
                    
                    $('.display_button').val(button_label_02);

                    $('tr:not(:only-of-type)').click(function(){
                            $(this).hide();
                            $('.display_button').val(button_label_01);
                            $('.display_button').removeClass('disabled');
                        });
                    $('.display_button').click(function(){
                        $('tr').show();
                        $('.display_button').val(button_label_02);
                    });
                });


```

2019-03-17 20:33 UTC, pluhin approved these changes

2019-03-17 20:33 UTC, merged