Home task: 01_html
pluhin/sc.it-academy.by pull request #355
Opened 2019-03-17 19:48 UTC by AndreiYa

2019-03-17 20:30 UTC, pluhin requested changes
Just one remark, see comment

2019-03-17 20:30 UTC, pluhin commented on ayakimenko/01_HTML/Task-1.html
> +		«Шоу Трейси Ульман» 19 апреля 1987 года. <!-- Демонстрация полноценных серий мультсериала началась 17 декабря 1989 года на канале FOX. Выпускается «Gracie Films» для кинокомпании
you didn't close paragraph here

2019-03-18 05:55 UTC, AndreiYa commented on ayakimenko/01_HTML/Task-1.html
> +		«Шоу Трейси Ульман» 19 апреля 1987 года. <!-- Демонстрация полноценных серий мультсериала началась 17 декабря 1989 года на канале FOX. Выпускается «Gracie Films» для кинокомпании
My mistake.

2019-03-18 08:06 UTC, pluhin approved these changes

2019-03-18 08:06 UTC, merged