Home task: HTML 01
pluhin/sc.it-academy.by pull request #356
Opened 2019-03-17 20:08 UTC by Aliaksei888

1_1 - text Python 1
1_2 - text Python 2
1_3 - text Python 3
1_Simpsons - text Illegible code

2019-03-17 20:29 UTC, pluhin requested changes

2019-03-17 20:29 UTC, pluhin commented on AliakseiShas/01_HTML/1_1.html
> +        <p><b>chmod +x hello.py</b></p>
it isn't paragraph

2019-03-17 20:29 UTC, pluhin commented on AliakseiShas/01_HTML/1_2.html
> +		<p>которая вернёт 12.</p>>
extra `>` in the end

2019-03-17 20:29 UTC, pluhin commented on AliakseiShas/01_HTML/1_2.html
> +		<p>#</p>
it isn't paragraph

2019-03-18 07:01 UTC, Aliaksei888 commented on AliakseiShas/01_HTML/1_2.html
> +		<p>которая вернёт 12.</p>>
I chenged

2019-03-18 08:12 UTC, pluhin approved these changes
Good, approved

2019-03-18 08:12 UTC, merged