My third tasks
pluhin/sc.it-academy.by pull request #407
Opened 2019-03-26 17:13 UTC by SokolovskyVadim

I do my third tasks, check it pls!

2019-03-27 09:46 UTC, pluhin requested changes

2019-03-27 09:46 UTC, pluhin commented on vsokolovsky/05.HTML/forms_1.html
> +                            +XXX-XX-XXXXXXX, где X - любое число</em><br>
Label is needed

2019-03-28 03:33 UTC, SokolovskyVadim commented on vsokolovsky/05.HTML/forms_1.html
> +                            +XXX-XX-XXXXXXX, где X - любое число</em><br>
I corrected the mistakes.

2019-03-29 11:15 UTC, pluhin approved these changes

2019-03-29 11:16 UTC, merged