M sc1 61 19
pluhin/sc.it-academy.by pull request #417
Opened 2019-03-28 08:28 UTC by AliaksandrTratsiak

css

2019-03-28 16:33 UTC, pluhin requested changes
Do not use Cyrillic  and whitespase in folder/file names. Could you please rename all file

2019-03-28 16:33 UTC, pluhin commented on atretiak/04_css/письмо/письмо.html
> +        <link type="text/css" rel="stylesheet" href="index.css">
I do not see link for font from google

2019-03-28 19:25 UTC, AliaksandrTratsiak commented on atretiak/04_css/письмо/письмо.html
> +        <link type="text/css" rel="stylesheet" href="index.css">
fix typo css

2019-03-28 19:27 UTC, AliaksandrTratsiak reviewed
fix typo css

2019-03-29 09:06 UTC, pluhin approved these changes
Good, approved

2019-03-29 09:06 UTC, merged