M sc1 61 19
pluhin/sc.it-academy.by pull request #460
Opened 2019-04-07 18:50 UTC by sergey-mario

This is my hometask "CSS 04".
But I can't understand how I can change align at right column using "not" (file "work_table"). That's why I did task whithout "not".

2019-04-07 19:59 UTC, pluhin commented
> This is my hometask "CSS 04".
> But I can't understand how I can change align at right column using "not" (file "work_table"). That's why I did task whithout "not".
```
tr:not(:nth-child(1)) th { text-align: left;}
```

2019-04-07 20:01 UTC, pluhin requested changes

2019-04-07 20:01 UTC, pluhin commented on smaretski/04_CSS/chess_board_num.html
> +    tr:nth-child(odd) > td:nth-child(even){
You can combine with next one

2019-04-07 20:01 UTC, pluhin commented on smaretski/04_CSS/chess_board.html
> +    tr:nth-child(odd) > td:nth-child(even){
you can combine with next one

2019-04-08 19:10 UTC, sergey-mario commented on smaretski/04_CSS/chess_board_num.html
> +    tr:nth-child(odd) > td:nth-child(even){
Combined

2019-04-08 19:10 UTC, sergey-mario commented on smaretski/04_CSS/chess_board.html
> +    tr:nth-child(odd) > td:nth-child(even){
Combined

2019-04-09 09:05 UTC, merged