Home task: HTML 01
pluhin/sc.it-academy.by pull request #495
Opened 2019-10-23 19:16 UTC by viktarradzin

all perfectly

2019-10-23 20:53 UTC, pluhin requested changes
See comments 
And do not use paragraph tag for code sections (better tag pre)

2019-10-23 20:53 UTC, pluhin commented on vradzin/01_HTML/task_3.html
> +    Давайте рассмотрим другой тип переменных, который называется <i>списки</i>. В других</br>
Paragraph here

2019-10-23 20:53 UTC, pluhin commented on vradzin/01_HTML/task_3.html
> +    <p></p>
What does empty paragraph do here?

2019-10-23 20:53 UTC, pluhin commented on vradzin/01_HTML/task_3.html
> +    <p><code>categories = ['Main dish','Meat','Fish','Soup','Cookies']</code></p>
there is no paragraph, code/pre

2019-10-23 20:53 UTC, pluhin commented on vradzin/01_HTML/task_4.html
> +    Модули предлагают способ расширить программирование на Python. Вы можете создать</br>
Paragraph here

2019-10-25 17:14 UTC, viktarradzin commented on vradzin/01_HTML/task_3.html
> +    Давайте рассмотрим другой тип переменных, который называется <i>списки</i>. В других</br>
<p><h2>Списки</h2></p>
<p>Давайте рассмотрим другой тип переменных, который называется <i>списки</i>. В других языках программирования они называются <i>массивами</i>. Если мы обратимся к аналогии с коробками для обуви, то массив (список) представляет собой несколько склеенных друг с  другом коробок с одинаковыми вещами. Например, в одной коробке лежат вилки, в другой — ножи, в третьей — ложки. Посмотрим на простой список— список месяцев. Мы  запрограммируем его так:</p>

2019-10-25 17:17 UTC, viktarradzin commented on vradzin/01_HTML/task_3.html
> +    <p></p>
<p>Давайте рассмотрим другой тип переменных, который называется <i>списки</i>. В других языках программирования они называются <i>массивами</i>. Если мы обратимся к аналогии с коробками для обуви, то массив (список) представляет собой несколько склеенных друг с другом коробок с одинаковыми вещами. Например, в одной коробке лежат вилки, в другой — ножи, в третьей — ложки. Посмотрим на простой список— список месяцев. Мы запрограммируем его так:</p> 
<pre><code>months =
      ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']</code></pre>

2019-10-25 17:22 UTC, viktarradzin commented on vradzin/01_HTML/task_3.html
> +    <p><code>categories = ['Main dish','Meat','Fish','Soup','Cookies']</code></p>
<p>Чтобы создать список, мы заключили все значения в квадратные скобки ( '[' и ']' ). Мы
 назвали наш список '<i>months</i>'. Чтобы использовать список, мы дадим команду print <strong>months[0]</strong> или <strong>months[1]</strong> (которые выведут на экран <i>'Jan'</i> или <i>'Feb'</i>). Помните: счет начинается с нуля. Чтобы найти длину списка, можно использовать такую функцию:</p>
<pre><code>print len(months)</code></pre>
<p>которая вернёт 12.</p>
<p>Ещё один пример списков — категории в поваренной книге. Например...</p>
<code>categories = ['Main dish','Meat','Fish','Soup','Cookies']</code>

2019-10-25 17:24 UTC, viktarradzin commented on vradzin/01_HTML/task_4.html
> +    Модули предлагают способ расширить программирование на Python. Вы можете создать</br>
<p>В прошлый раз мы изучали списки, подстановку переменных, комментарии, сравнение и присвоение, операторы if и while. Я обещал, что в этой части мы изучим модули и функции. Давайте начнём.</p>
<p><h2>Модули</h2></p>
<p>Модули предлагают способ расширить программирование на Python. Вы можете создать свои модули, использовать те, которые поставляются с Python или которые написали другие. В самом Python есть сотни модулей, которые облегчают написание программ.Список модулей, поставляемых с Python, находится по адресу:</p>

2019-10-27 20:08 UTC, pluhin requested changes
See comments

2019-10-27 20:08 UTC, pluhin commented on vradzin/01_HTML/task_3.html
> +    <p><code>#</code></p>
need to remove paragraph here

2019-10-27 20:08 UTC, pluhin commented on vradzin/01_HTML/task_3.html
> +    Давайте рассмотрим другой тип переменных, который называется <i>списки</i>. В других</br>
missing paragraph

2019-10-27 20:08 UTC, pluhin commented on vradzin/01_HTML/task_2.html
> +    Из множества существующих языков программирования Python — один из самых лёгких<br/>
missing paragraph

2019-10-28 18:32 UTC, viktarradzin reviewed
Home Task 02

2019-10-30 12:04 UTC, closed without merging