Md sc1 65 19
pluhin/sc.it-academy.by pull request #518
Opened 2019-11-08 11:27 UTC by viktarradzin

Home work

2019-11-08 15:30 UTC, pluhin requested changes

2019-11-08 15:30 UTC, pluhin commented on vradzin/05_HTML/task_01.html
> +        .s_1 {
Could you please minimize that CSS

2019-11-11 08:08 UTC, pluhin requested changes

2019-11-11 08:08 UTC, pluhin commented on vradzin/05_HTML/task_01.html
> +        .s_1 {
Still pending

2019-11-11 13:29 UTC, viktarradzin commented on vradzin/05_HTML/task_01.html
> +        .s_1 {
add new code

2019-11-11 21:12 UTC, pluhin approved these changes
Good, approved

2019-11-11 21:12 UTC, merged